### ISSUE TITLE
Support for USB interfaces?

### ISSUE THREAD

**Issue by ItsProfessional** [lal12/macroMyKBD#23]
For my specific keyboard, there is a third field next to USB ID, which is the interface field, which is also shown next to the device name at the top
(Note: the screenshot is from a vm running in vmware, but when I tried it on my host, it was the same. Just the device name is "USB Keyboard" instead of "VMware". There is still a third field for the interface.)

The installation guide in the README of this repository  does not mention the interface at all. I tried to install the driver for the first interface, in the 2nd interface, in both of them. But in all cases when I try to use the first two fields in mmkbd, it just shows a lot of errors. I think this is because it doesn't have support for interfaces or something, I'm not entirely sure.

![Screenshot_1](https://user-images.githubusercontent.com/63961221/215275359-1142f23f-4c69-4a11-9f67-b880f11f0c01.png)

**Comment by ItsProfessional** [comment]
I fixed it

**Comment by TarkanV** [comment]
Would you bother to explain how even briefly x) ?
I mean, otherwise might as well close it without throwing the "I fixed it" :v
I mean technically I didn't experience this issue even though I have two interfaces that appear for my usb keyboard, but I have another issue where numpad lock and caps lock keys light indicators don't work anymore after installing the driver and I wonder if it is related to the other interface for which I didn't swap the driver.
